<template>
  <a-row :gutter="[24, 24]" :wrap="true">
    <BaseWidget
      :height="110"
      title="Supplier"
      :value="answersStore.getTotalIpAddress"
      :icon="SettingOutlined"
      description="Counted supplier listed on database"
    />
    <BaseWidget
      :height="110"
      title="Major"
      :value="answersStore.getTotalMajor"
      :icon="ExclamationCircleOutlined"
      description="Counted major listed on database"
    />
    <BaseWidget
      :height="110"
      title="Resume"
      description="The resume is generated by the Ollama AI module (Gemma3:270m) based on data stored in the database"
      :icon="AlignCenterOutlined"
    />
  </a-row>
</template>

<script setup>
import { onMounted } from 'vue'
import BaseWidget from '@/components/base/BaseWidget.vue'
import { useAnswersStore } from '@/stores/answers'
import {
  SettingOutlined,
  ExclamationCircleOutlined,
  AlignCenterOutlined,
} from '@ant-design/icons-vue'
const answersStore = useAnswersStore()

onMounted(() => {
  answersStore.fetchAnswers() // ini yang ambil data dari backend
})
</script>

<style scoped></style>
